USE toolshare;

-- Sample Tools with realistic high quality Unsplash images & Dual Pricing (Hourly & Daily) across major Indian cities
INSERT INTO tools (lender_id, tool_name, category, description, tool_condition, location, hourly_rate, daily_rate, image_url, availability_status)
VALUES 
-- Power Tools & Handheld Equipment
(2, 'Bosch Professional Cordless Hammer Drill 18V', 'Power Tools', 'Heavy duty 18V brushless motor with 2 batteries, charger, and 30-piece drill & driver set in carrying case. Perfect for masonry, wood, and steel.', 'Like New', 'Bengaluru - Koramangala', 30.00, 180.00, 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=800&q=80', 'AVAILABLE'),
(2, 'DeWalt 12-Inch Dual-Bevel Sliding Compound Miter Saw', 'Power Tools', 'Precise miter system with machined base fence support. Includes 60T carbide blade and dust bag. Ideal for crown molding and wood framing.', 'Good', 'Mumbai - Andheri West', 50.00, 320.00, 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=800&q=80', 'AVAILABLE'),
(2, 'Kärcher K5 Premium Smart Control High Pressure Washer', 'Cleaning', '2100 PSI pressure washer with 3-in-1 multi-jet lance, plug & clean detergent system. Excellent for cars, patios, and outdoor driveways.', 'Brand New', 'Delhi NCR - Connaught Place', 40.00, 240.00, 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80', 'AVAILABLE'),
(2, 'Werner 20-Foot Aluminum Telescoping Extension Ladder', 'Construction', 'Type IA 300 lb duty rating. Smooth operating pulley and slip-resistant traction rung shoes. Great for roof repair and painting.', 'Good', 'Hyderabad - Hitec City', 25.00, 150.00, 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80', 'AVAILABLE'),
(2, 'Stihl Gas Powered String Trimmer & Brushcutter', 'Gardening', 'High efficiency 2-stroke engine with easy-start system. Includes dual-line bump head and shoulder harness for landscaping.', 'Good', 'Chennai - Central', 35.00, 210.00, 'https://images.unsplash.com/photo-1617576683096-00fc8eecb3af?auto=format&fit=crop&w=800&q=80', 'AVAILABLE'),
(2, 'Makita Variable Speed Angle Grinder 4-1/2 Inch', 'Workshop', '11 Amp motor with paddle switch and lock-on. Includes 5 cutting and grinding discs and side handle.', 'Like New', 'Pune - Kothrud', 20.00, 120.00, 'https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&w=800&q=80', 'AVAILABLE'),
(2, 'Craftsman 450-Piece Mechanics Tool Set with 3-Drawer Box', 'Automotive', 'Comprehensive 1/4, 3/8, and 1/2 inch drive ratchets, sockets, wrenches, and specialty hex keys. Perfect for DIY car maintenance.', 'Brand New', 'Kolkata - Salt Lake', 45.00, 260.00, 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=800&q=80', 'AVAILABLE'),
(2, 'Stanley FatMax 1000A Peak Jump Starter with Compressor', 'Automotive', 'Instant jump-starting power with reverse polarity alarm and 120 PSI digital air compressor with autostop.', 'Good', 'Ahmedabad - SG Highway', 25.00, 140.00, 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=800&q=80', 'AVAILABLE'),

-- Heavy Construction Machinery, Vehicles, and Agricultural Equipment
(2, 'JCB 3DX EcoXcellence Backhoe Loader (76HP)', 'Heavy Machinery', 'Heavy-duty 76HP Turbo engine backhoe loader with 6-in-1 multipurpose front bucket and 0.24 cu.m excavator bucket. Includes experienced certified operator option. Perfect for plot leveling, foundation trenching, demolitions, and heavy soil loading.', 'Like New', 'Bengaluru - Whitefield', 1200.00, 9500.00, 'https://images.unsplash.com/photo-1580983218765-f663bec07b37?auto=format&fit=crop&w=800&q=80', 'AVAILABLE'),
(2, 'Mahindra 575 DI 45HP Tractor with 3-Ton Hydraulic Trolley', 'Tractors & Farm', '45HP high-torque diesel tractor fitted with heavy-duty twin-wheel hydraulic tipping trolley. Ideal for transporting construction sand, bricks, farm produce, and field soil plowing.', 'Good', 'Hyderabad - Gachibowli', 500.00, 3800.00, 'https://images.unsplash.com/photo-1592878904946-b3cd8ae243d0?auto=format&fit=crop&w=800&q=80', 'AVAILABLE'),
(2, 'Tata 407 SFC Heavy Duty Tipper Dump Truck (3.5T)', 'Transport & Load', 'Reliable 4-wheeler diesel tipper truck with automatic hydraulic lifting bed. Specially suited for quick construction debris disposal, gravel hauling, and bulk cement transport across city zones.', 'Like New', 'Mumbai - Bandra', 450.00, 3200.00, 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=800&q=80', 'AVAILABLE'),
(2, 'Kubota U35-4 3.5-Ton Zero Tail-Swing Mini Excavator', 'Heavy Machinery', 'Compact rubber-tracked excavator designed for tight residential building zones, drainage pipe excavation, and swimming pool digging. Emits low noise and preserves paved ground.', 'Brand New', 'Delhi NCR - Gurgaon Cyber City', 850.00, 6500.00, 'https://images.unsplash.com/photo-1584463699042-4b2674e2d24d?auto=format&fit=crop&w=800&q=80', 'AVAILABLE'),
(2, 'Diesel Powered Concrete Mixer Machine (1-Bag / 10/7 CFT)', 'Construction', 'Heavy gauge drum concrete mixer powered by 6HP air-cooled diesel engine with towing bar. Ensures rapid, uniform mixing of cement, sand, and aggregate for pillar foundation and slab work.', 'Good', 'Chennai - Anna Nagar', 150.00, 900.00, 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80', 'AVAILABLE'),
(2, 'Caterpillar 226D3 Skid Steer Loader (Bobcat)', 'Heavy Machinery', 'Ultra-versatile compact loader with quick hydraulic coupler and 66-inch dirt bucket. Exceptional agility for site cleanup, gravel spreading, and moving materials inside enclosed work sites.', 'Like New', 'Pune - Hinjewadi', 750.00, 5600.00, 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?auto=format&fit=crop&w=800&q=80', 'AVAILABLE'),

-- Professional Hand Tools & Workshop Essentials
(2, 'Stanley 16oz Fiberglass Curved Claw Hammer', 'Hand Tools', 'Forged carbon steel head with polished smooth face, magnetic nail starter groove, and vibration-dampening ribbed fiberglass handle. Excellent balance for carpentry, furniture assembly, and heavy nail driving.', 'Brand New', 'Mumbai - Dadar', 5.00, 25.00, 'images/Hammer.jpeg', 'AVAILABLE'),
(2, 'Stanley 10-Inch Chrome Adjustable Wrench (Spanner)', 'Hand Tools', 'Forged alloy steel adjustable wrench with corrosion-resistant chrome finish and laser-etched metric & imperial jaw scale. Wide 34mm jaw opening for plumbing pipes, automobile nuts, and home maintenance.', 'Brand New', 'Bengaluru - Koramangala', 6.00, 35.00, 'images/Adjustable wrench.jpeg', 'AVAILABLE'),
(2, 'Taparia 9-Piece Long Arm Ball End Hex Allen Key Set', 'Hand Tools', 'High-tensile chrome vanadium steel hex keys (1.5mm to 10mm). Ball end permits up to 25-degree tilt for tight and awkward angles. Includes folding organizer bracket.', 'Brand New', 'Delhi NCR - Connaught Place', 4.00, 20.00, 'images/Allen key.jpeg', 'AVAILABLE'),
(2, 'Heavy Duty 6-Inch Cast Iron C-Clamp (G-Clamp)', 'Hand Tools', 'High-strength ductile iron body with smooth acme-threaded steel screw, sliding T-handle, and swivel pad. Ideal for woodworking joinery, metal fabrication, welding jigs, and glue setups.', 'Like New', 'Chennai - Central', 6.00, 30.00, 'images/C - Clamp.jpeg', 'AVAILABLE'),
(2, 'Stanley 20-Inch Heavy Duty Woodcutting Hand Saw', 'Hand Tools', 'Precision induction-hardened triple-ground teeth cutting on both push and pull strokes. Ergonomic bi-material slip-free handle with built-in 45 and 90 degree square marking guides for fast carpentry timber cutting.', 'Brand New', 'Hyderabad - Hitec City', 8.00, 40.00, 'images/Hand saw.jpeg', 'AVAILABLE'),
(2, 'Freemans 5-Meter Heavy Duty Steel Measuring Tape', 'Hand Tools', 'Class II certified abrasion-resistant nylon-coated steel blade with clear millimeter and inch graduations. Features positive thumb lock, true-zero magnetic hook, and impact-absorbing rubberized casing.', 'Brand New', 'Bengaluru - Whitefield', 3.00, 15.00, 'images/Measuring tape.jpeg', 'AVAILABLE'),
(2, 'Ridgid Style 14-Inch Heavy Duty Cast Iron Pipe Wrench', 'Hand Tools', 'Heavy-duty ductile iron I-beam handle with full-floating forged alloy hook jaw with deep self-cleaning milled teeth. Non-stick knurled adjustment nut. Designed for tough plumbing and GI pipe fittings up to 2 inches (50mm).', 'Good', 'Pune - Kothrud', 8.00, 45.00, 'images/Pipe wrench.jpeg', 'AVAILABLE'),
(2, 'Taparia 8-Piece Multi-Bit Magnetic Screwdriver Set', 'Hand Tools', 'High-grade silicon manganese steel blades with strong magnetized tips. Set includes flat slotted, Phillips, and electrical line tester with ergonomic textured high-torque grips for appliances, PC build, and electrical fixtures.', 'Brand New', 'Kolkata - Salt Lake', 5.00, 25.00, 'images/Screwdriver.jpeg', 'AVAILABLE');
